create table cartao (id varchar(255) not null, emitido_em varchar(255), limite numeric(19, 2), titular varchar(255), proposta_id int8, primary key (id));
create table endereco (id int8 generated by default as identity, bairro varchar(255), complemento varchar(255), logradouro varchar(255), uf varchar(2), proposta_id int8, primary key (id));
create table proposta (id int8 generated by default as identity, data_registro TIMESTAMP WITHOUT TIME ZONE, documento varchar(255), email varchar(255), nome varchar(255), salario numeric(19, 2) not null, status_proposta varchar(255), update_data_registro TIMESTAMP WITHOUT TIME ZONE, cartao_id varchar(255), primary key (id));
alter table if exists proposta add constraint UK_ay0la7s80cky229aexg8pyvod unique (documento);
alter table if exists cartao add constraint FKp9vgcwkig6ql7r93tbll6dvn0 foreign key (proposta_id) references proposta;
alter table if exists endereco add constraint FKtqdwr0m63311ns0ee96iw2yqi foreign key (proposta_id) references proposta;
alter table if exists proposta add constraint FKe1lujotcy5ybcosbovmu3g22k foreign key (cartao_id) references cartao;
